language: python
cache: pip
python:
  - 3.6
  - 3.7
  - 3.8
os:
  - linux
  - osx
  - windows
install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt  # coverage inside reqs
script: coverage run -m unittest discover
after_success: bash <(curl -s https://codecov.io/bash) || echo 'Codecov failed to upload'://codecov.io/bash) || echo 'Codecov failed to upload'